name: superlinter

on: 
  push:

jobs:
  super-linter:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v3.14.4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_YAML: false
